openapi: 3.0.3
info:
  title: Smart Home API
  version: 1.0.0

paths:
  /devices:
    post:
      summary: Register new device
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Server error
  /devices/{device_id}:
    get:
      summary: Get device data
      parameters:
        - in: path
          name: device_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Server error

  /devices/{device_id}/status:
    patch:
      summary: Set device status
      parameters:
        - in: path
          name: device_id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
      responses:
        '202':
          description: Accepted
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Server error

  /devices/{device_id}/commands:
    post:
      summary: Send command to device
      parameters:
        - in: path
          name: device_id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  type: object
      responses:
        '202':
          description: Accepted
        '401':
          description: Unauthorized
        '404':
          description: Device not found
        '500':
          description: Server error

  /devices/{device_id}/telemetry:
    post:
      summary: Create new telemetry record
      parameters:
        - in: path
          name: device_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TelemetryData'
        '401':
          description: Unauthorized
        '404':
          description: Device not found
        '500':
          description: Server error
    get:
      summary: Get historical telemetry data
      parameters:
        - in: path
          name: device_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TelemetryData'
        '401':
          description: Unauthorized
        '404':
          description: Device not found
        '500':
          description: Server error
  
  /devices/{device_id}/telemetry/latest:
    get:
      summary: Get latest telemetry data
      parameters:
        - in: path
          name: device_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TelemetryData'
        '401':
          description: Unauthorized
        '404':
          description: Device not found
        '500':
          description: Server error

components:
  schemas:
    Device:
      type: object
      properties:
        device_id:
          type: string
          format: uuid
        serial_number:
          type: string
        type:
          type: string
        status:
          type: string

    TelemetryData:
      type: object
      properties:
        device_id:
          type: string
          format: uuid
        data:
          type: object
